# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christa Elliott's scrumdiddlyumptious website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Japanese submarine slammed two torpedoes into our side, Chief. We was comin'back
  from the island of Tinian to Leyte... just delivered the bomb. The Hiroshima bomb.
  Eleven hundred men went into the water. Vessel went down in 12 minutes. Didn't see
  the first shark for about a half an hour. Tiger. Thirteen footer. You know... you
  know that when you're in the water, chief? You tell by lookin' from the dorsal to
  the tail. Well, we didn't know... 'cause our bomb mission had been so secret, no
  distress signal had been sent, huh. They didn't even list us overdue for a week.
  Very first light, chief. The sharks come cruisin'. So we formed ourselves into tight
  groups. You know it's... kinda like 'ol squares in battle like uh, you see on a calendar,
  like the Battle of Waterloo. And the idea was, the shark goes to the nearest man and
  then he'd start poundin' and hollerin' and screamin' and sometimes the shark would go away.
  Sometimes he wouldn't go away. Sometimes that shark, he looks right into you. Right into
  your eyes. You know the thing about a shark, he's got... lifeless eyes, black eyes, like
  a doll's eye. When he comes at ya, doesn't seem to be livin'. Until he bites ya and those
  black eyes roll over white. And then, ah... then you hear that terrible high pitch screamin'
  and the ocean turns red and spite of all the poundin' and the hollerin' they all come in
  and rip you to pieces. Y'know by the end of that first dawn, lost a hundred men! I don't
  know how many sharks there were... maybe a thousand! I don't know how many men, they
  averaged six an hour. On Thursday mornin' chief, I bumped into a friend of mine,
  Herbie Robinson from Cleveland. Baseball player, Bosun's Mate. I thought he was asleep,
  reached over to wake him up. He bobbed up and down in the water, just like a kinda top.
  Up ended him into a raft. Well... he'd been bitten in half below the waist. At noon
  on the fifth day, Mr. Hooper, a Lockheed Ventura saw us, he swung in low and he saw us.
  He was a young pilot, a lot younger than Mr. Hooper... anyway he saw us and come in low.
  And three hours later a big fat PBY comes down and start to pick us up. You know that
  was the time I was most frightened. Waitin' for my turn. I'll never put on a lifejacket
  again. So, eleven hundred men went in the water, three hundred and sixteen men come out,
  the sharks took the rest, June the 29th 1945. Anyway, we delivered the bomb.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
